ld-lanrds:
    container_name: ld-landrs
    build: ./trifid
    ports:
      - 80:8080
    links:
      - fuseki-landrs

fuseki-landrs:
    container_name: fuseki-landrs
    build: ./fuseki-geosparql-docker
    volumes:
      - ./data/dronekg.rdf:/jena-fuseki/geosparql_test.rdf
    ports:
      - 3030:3030
    expose:
      - "3030"
